### ISSUE TITLE
'FILETIME' was not declared in this scope

### ISSUE THREAD

**Issue by liafalk** [HPCE/hpce-2016-cw6#1]
Hi, when I try to compile the reference in windows x64, I get this error:
```
In file included from src/ref/simulator.cpp:1:0:
include/util.hpp: In function 'puzzler::timestamp_t puzzler::now()':
include/util.hpp:100:5: error: 'FILETIME' was not declared in this scope
     FILETIME ft;
     ^~~~~~~~
```
Unless I did something weird, I think the code is missing an include to windows.h?

edit: Speaking to others it seems like I was the only one with this... I guess I am in some weird position where I didn't match the correct platform directives or something (I'm using MSYS2).

**Comment by m8pple** [comment]
Ok - I was looking into it just now, but didn't see the same behaviour. At least it's easy to correct,
just make sure the #include is guarded so it doesn't crop up under linux.
