### ISSUE TITLE
Error in generate_heat_rect?

### ISSUE THREAD

**Issue by pm1113** [HPCE/hpce-2016-cw6#14]
Hello, I was wondering if there was an error in the following code:

```
if(argc>1){
    w=atoi(argv[1]);
    h=w;
}
if(argc>2){
    maxTime=atoi(argv[2]);
}
if(argc>3){
    outputDeltaTime=atoi(argv[3]);
}
if(argc>4){
    outputDeltaSpace=atoi(argv[3]);
}
```

The output delta time and space are both referencing the same input argument?

**Comment by eugenius1** [comment]
Also, the readme has the other order
"4 spatially and 8 temporally"

**Comment by m8pple** [comment]
Ah - yes. Good catch. I mostly tested spatial and temporal varying at a similar
rate and node scaling, so must have missed that.

Thanks!
