### ISSUE TITLE
Dirichlet Values

### ISSUE THREAD

**Issue by ps1213** [HPCE/hpce-2016-cw6#18]
When we 'play' the .mjpeg files - I noticed that the Dirichlet nodes are also changing colour with time (boundary nodes). I am quite confused by this as I thought the Dirichlet values are not affected at all during the simulation and stay a constant value. Not sure if I'm missing something.

**Comment by m8pple** [comment]
Dirichlet cells are forced by some external process, so those points on the
grid are forced to some particular value, and the other cells have to
respond to them. One example in an electrical sense would be "ground",
which is defined to always be zero, no matter what else happens. However,
they can also be time-varying, so when you have some time varying
voltage source V(t), then that is still a Dirichlet condition, as it forces
the node to have the value V(t) at time t, and all the other nodes have
to somehow catch-up (e.g. capacitors charge, inductors discharge etc.).

In the heat scenario, a dirichlet cell is one that is driven by some
external process to ensure that chosen heat. You could imagine some kind
of temperature source with a feed-back loop, similar to the feedback
loop needed in a voltage source that adjusts to the load.

In this simulation we still need time varying solutions to make things
realistic, but I was limited in terms of how complex I could make it,
so the dirichlet cells follow [a very simple process](https://github.com/HPCE/hpce-2016-cw6/blob/master/include/graphs/heat.hpp#L134-L139). But they are still
time-varying, as you see in the output.

For completeness, the other typical condition is Von Neuman, which
enforces a particular flux (derivative) on the cell. In the heat example
it is equivalent to applying a heat source, but without ensuring a
particular temperature. In the electrical case, it would be equivalent
to a current source which didn't attempt to achieve a particaly
voltage.

Much of what you're seeing in heat has a natural analogy to
solving time-dependent electrical circuits (as seen in 1st year
analysis of circuits). The main thing stopping your simulator
doing time-dependent LCR networks is that it can't deal with
reactive mass - that would require us to solve a linear equation
at each time step, and so would essentially become SPICE.
