### ISSUE TITLE
step_node log statement bug

### ISSUE THREAD

**Issue by akasture1** [HPCE/hpce-2016-cw6#19]
Hi,

minor issue but for completeness I believe the last argument of the following statement in the step_node method

`log(3, "  node %u : blocked on %u->%u", index, n->outgoing[i]->src->properties.id, n->outgoing[i]->src->properties.id);`

should contain **dst**->properties.id instead of **src**->properties.id i.e.

`log(3, "  node %u : blocked on %u->%u", index, n->outgoing[i]->src->properties.id, n->outgoing[i]->dst->properties.id);`

Thanks

**Comment by m8pple** [comment]
Thanks - yes, you're right.

(I'm on train wifi at the moment so can't fix, but will correct when I'm back on stable internet).
