### ISSUE TITLE
heat.selfWeight always stays constant?

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw6#21]
Hi,

While we were testing we found that the heat.selfWeight is always an array of a single constant number. Can we assume that this is always the case?

Thank you

Best, awai54st

**Comment by m8pple** [comment]
It is always constant for a given device, as it is part of the device properties.
So within one simulation, none of the weights will change.

However, it will vary between different devices in a graph.

**Comment by awai54st** [comment]
Hi,

Can you specify what you mean by "device"? Does that mean each node in a graph can have different selfWeight?

Thank you 

Best, awai54st

**Comment by m8pple** [comment]
Yes, each node in the graph could have a different selfWeight.

It's roughly the same as having a conductivity which varies, with some
parts having higher resistance (e.g. thinner or larger sections in a resistive wire).
