### ISSUE TITLE
Open CL setup within a class?

### ISSUE THREAD

**Issue by sagarpatel9410** [HPCE/hpce-2016-cw6#23]
I am trying to add open cl code to aspects of the SupervisorDevice class, however I am running into the following error:

`Command terminated by signal 11 `

I have read that this is a segmentation fault of sorts which has been caused by making the kernel, context and queue member variables of the SupervisorDevice class. Is there an alternative to making these variables member variables which allows me call different opencl functions in different functions within the same class.

For example I would like to call `  queue.enqueueWriteBuffer();` in the constructor and maintain that queue in the function `onDeviceOutput()`

**Comment by m8pple** [comment]
A signal 11 could be many things - without stepping through in a debugger
it is difficult to say. It is often worth using an OpenCL software provider and
running it under a debugger to see if you can work out where the problem
is more precisely.

It's possible that there is a problem having the context et. al. be member variables,
but this would usually happen if the class is being copied in some odd way. That
said, I agree that making the scope of the variables not tied to the scope of the
class may well fix things.

So your options are going to be:
- global variables
- static member variables (i.e. global variables within a namespace)
- a singleton
- a function with static local variables (weak singleton)

A weak singleton version of this can work ok for this kind of
project, where you know the scope of how the class is going to
be used.

So for example, using the singleton/static function approach, you could have:

````
struct MyClass
{
   struct opencl_ctxt
   {
      cl::Context context;
      cl::Device device;
      ....
   };

     // Initialises everything if needed, otherwise just returns it
     opencl_vars *getCtxt()
     {
              static opencl_ctxt *ctxt=0;
              if(ctxt==0){
                  ctxt = new opencl_ctxt;
                  ctxt -> context = cl::Context(...);
                  ctxt -> device = cl::Device(...);
              }
              return ctxt;
     }

    MyClass()
    {
        getCtxt();  // Force it to be initialised
     }

    void step()
    {
        clEnqueue( getCtxt()->device, ...);
    }
};
````

This is not a brilliant solution, but it means that opencl gets
initialised precisely once, and tends to avoid bugs associated
with stomping over class variables (or at least make them
more visible).
