### ISSUE TITLE
Buffer persistence through two kernel functions?

### ISSUE THREAD

**Issue by liafalk** [HPCE/hpce-2016-cw6#26]
Hi,
I've written two kernel functions within one file, and they both use the same global buffers. The first kernel function does some operations on the buffers, but when the second kernel is enqueued, it doesn't seem to get the updated global buffer (To test this, I printf'd the accessed values from the global buffers within each kernel). 

Is this not possible or am I doing something wrong? I'm just enqueuing both kernels one after the other (with barriers).

Thanks!

**Comment by liafalk** [comment]
Okay I can't delete this but I was looking at something else...It's working fine, the problem is on my end. Sorry ><

**Comment by jeremych1000** [comment]
@indigoDot How did you solve it? I think I've got the same problem.
