### ISSUE TITLE
For anyone else who is using the node IDs and having some problems. 

### ISSUE THREAD

**Issue by pm1113** [HPCE/hpce-2016-cw6#33]
I noticed that the node's IDs for the three graph types are a bit off.

For rect, the node ids start from 0 whereas for hex and mesh they start from 1. 

Ideally, I hope that the reference for generating graphs will be changed however since Dr. Thomas is no around, I have put in a check in my code to deduce what the first id is.

**Comment by m8pple** [comment]
Yes, there's no particular guarantee on what order the ids come in. They
tend to be sequential as a consequence of the generation process, but
in principle they don't have to be. For some graphs they could end up
being sparse. Usually id is taken to mean unique, with a sequential
id as a stronger condition.

However, I don't intentionally generate non-sequential ids.
