### ISSUE TITLE
Last run logs missing

### ISSUE THREAD

**Issue by aw1513** [HPCE/hpce-2016-cw6#34]
As far as I know you did another test run last night, but I seem to not be able to see the branch dt10_runs_4. What can be the reason for this?
Thanks!

**Comment by m8pple** [comment]
Looks like the build failed, and the script didn't push the results:

g++: error: OpenCL: No such file or directory
g++: error: unrecognized command line option ‘-framework’
make[1]: *** [bin/user/simulator] Error 1
outputs/aw1513/build.stderr (END)

**Comment by aw1513** [comment]
Thanks. Seems like the mac-makefile was on the master branch. Good to know for the submission!
