### ISSUE TITLE
Formal way to include our own hpp files?

### ISSUE THREAD

**Issue by awai54st** [HPCE/hpce-2016-cw6#4]
Hi,
Is there a formal way to include our own hpp files while keeping the include/*.hpp files untouched? Cos we are worried that our way of including the hpp may conflict with your auto-testing methodology. 
Thank you
Best, awai54st

**Comment by narobertson42** [comment]
You can easily add a directory within `include` called `user`, you wouldn't have any merge conflicts assuming @m8pple doesn't decide to create the same directory. 

Alternatively if you are set on not changing anything about the `include` directory you could create a new directory in the root directory called something along the lines of `userIncludes` and you would simply need to add it to the makefile
`CPPFLAGS += -std=c++11 -W -Wall -g -O3 -I include -I userIncludes`

**Comment by m8pple** [comment]
Yes, I agree with @nar213 - you can just create directories which will never conflict
with me (your login name is not a bad choice, as I'll be working in dt10_runs for
the auto runs.).
