### ISSUE TITLE
Statistic Data

### ISSUE THREAD

**Issue by sagarpatel9410** [HPCE/hpce-2016-cw6#9]
What data do you mean when you say: 

One thing the simulator produces is a stream of statistics, explaining what the devices and edges were doing in each hardware "time step". This should match the output of the reference simulator.

Is this referring to code in the simulator that looks like this:
` m_stats.edgeIdleSteps++;`

If so as it must match the output of the reference does that mean we cannot make optimizations which for example skip the data transfer process between boundary nodes?

Also can you highlight an example of the statistic:

The simulator also produces a stream of statistics, which describes what the simulated hardware is doing in terms of simulated CPU and network activity.

**Comment by m8pple** [comment]
The statistics are the numbers collected in the [`stats` structure](https://github.com/HPCE/hpce-2016-cw6/blob/master/include/simulator.hpp#L57-L68).

The actual output is what is [written to the first output stream](https://github.com/HPCE/hpce-2016-cw6/blob/master/include/simulator.hpp#L306-L308).

It appears in the output as lines like this:

```
0, 0, 0, 911, 5280, 0, 0
1, 910, 1, 0, 0, 4848, 432
2, 893, 18, 0, 432, 3683, 1165
3, 753, 158, 0, 1597, 2173, 1510
4, 463, 448, 0, 3107, 913, 1260
```

In terms of optimisations, you can skip the act of doing something,
as long as the statistics coming out are correct.

**Comment by wct3** [comment]
@m8pple From this can I infer that for any given input, as long as `diff ref.stats user.stats` are equal, then the user program is giving the correct output? Since at every hardware time step it all matches up.

**Comment by m8pple** [comment]
@wct3 Yes, that's correct.

I think in my checking version it tolerates white-space changes, but just diffing
works fine too.
